"""Ianuacare: healthcare data pipeline and AI inference framework."""

from ianuacare.ai import (
    AIProvider,
    BaseAIModel,
    CallableProvider,
    DiarizationModel,
    LLMModel,
    ModelOutNormalizer,
    NLPModel,
    PauseParser,
    SpeakerClusterer,
    SpeakerEmbedder,
    SpectralParser,
    SpeechTranscriptionProvider,
    TextEmbedder,
    TogetherAIProvider,
    Transcription,
)
from ianuacare.core.audit import AuditService
from ianuacare.core.auth import (
    AuthService,
    CognitoAccountService,
    CognitoLoginService,
    CognitoRegistrationService,
    UserRepository,
)
from ianuacare.core.config import ConfigService, EnvConfigService
from ianuacare.core.exceptions import (
    AuthenticationError,
    AuthorizationError,
    IanuacareError,
    InferenceError,
    OrchestrationError,
    StorageError,
    ValidationError,
)
from ianuacare.core.logging import StructuredLogger
from ianuacare.core.models import (
    DataPacket,
    LoginTokens,
    PasswordResetDelivery,
    RegistrationResult,
    RequestContext,
    User,
    UserProfile,
)
from ianuacare.core.orchestration import InputDataParser, Orchestrator, OutputDataParser
from ianuacare.core.pipeline import (
    BucketContentType,
    DataManager,
    DataValidator,
    PassthroughStorageInputParser,
    PassthroughStorageOutputParser,
    Pipeline,
    PipelineDatabase,
    PipelineModel,
    StorageInputParser,
    StorageOutputParser,
)
from ianuacare.infrastructure import (
    CacheClient,
    EncryptionService,
    InMemoryCacheClient,
    NoOpEncryption,
)
from ianuacare.infrastructure.storage import (
    BucketClient,
    DatabaseClient,
    InMemoryBucketClient,
    InMemoryDatabaseClient,
    InMemoryVectorDatabaseClient,
    PostgresDatabaseClient,
    QdrantDatabaseClient,
    Reader,
    S3BucketClient,
    VectorDatabaseClient,
    Writer,
)
from ianuacare.presets import IanuacareStack, create_stack

__version__ = "0.3.0"

__all__ = [
    "AIProvider",
    "CallableProvider",
    "DiarizationModel",
    "AuditService",
    "AuthService",
    "AuthenticationError",
    "CognitoAccountService",
    "CognitoLoginService",
    "CognitoRegistrationService",
    "AuthorizationError",
    "BaseAIModel",
    "BucketContentType",
    "BucketClient",
    "CacheClient",
    "ConfigService",
    "EnvConfigService",
    "DataManager",
    "DataPacket",
    "DataValidator",
    "DatabaseClient",
    "IanuacareError",
    "InferenceError",
    "InMemoryBucketClient",
    "InMemoryCacheClient",
    "InMemoryDatabaseClient",
    "InMemoryVectorDatabaseClient",
    "InputDataParser",
    "LLMModel",
    "NLPModel",
    "ModelOutNormalizer",
    "PauseParser",
    "OrchestrationError",
    "Orchestrator",
    "OutputDataParser",
    "PassthroughStorageInputParser",
    "PassthroughStorageOutputParser",
    "Pipeline",
    "PipelineDatabase",
    "PipelineModel",
    "PostgresDatabaseClient",
    "QdrantDatabaseClient",
    "Reader",
    "RequestContext",
    "SpeakerClusterer",
    "SpeakerEmbedder",
    "SpeechTranscriptionProvider",
    "SpectralParser",
    "S3BucketClient",
    "StorageInputParser",
    "StorageOutputParser",
    "StructuredLogger",
    "StorageError",
    "TextEmbedder",
    "TogetherAIProvider",
    "Transcription",
    "EncryptionService",
    "NoOpEncryption",
    "User",
    "UserRepository",
    "ValidationError",
    "VectorDatabaseClient",
    "Writer",
    "IanuacareStack",
    "create_stack",
    "LoginTokens",
    "PasswordResetDelivery",
    "RegistrationResult",
    "UserProfile",
]
